import { getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, doc, setDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
let cloudProperties = [];
let brokers = {};
let activeFilter = "";

const $ = id => document.getElementById(id);
const esc = v => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const digits = v => String(v || "").replace(/\D/g, "");
const norm = v => String(v || "").trim().toLowerCase().replace(/[\s_-]+/g, " ");
function localProperties(){try{const p=JSON.parse(localStorage.getItem("realynkProperties")||"[]");return Array.isArray(p)?p:[]}catch{return[]}}
function localProfile(){try{return JSON.parse(localStorage.getItem("realynkBrokerProfile")||"{}")}catch{return{}}}
function typeOf(p){return p.type||p.listingType||p.listing_type||""}
function descriptionOf(p){return p.description||p.desc||""}
function photosOf(p){return Array.isArray(p.photoUrls)?p.photoUrls:(Array.isArray(p.photos)?p.photos:[])}
function allProperties(){const map=new Map();[...cloudProperties,...localProperties()].forEach(p=>{const key=String(p.id||p.propertyId||(p.title+"|"+p.area+"|"+typeOf(p)));if(!map.has(key))map.set(key,{...p});else map.set(key,{...map.get(key),...p})});return [...map.values()].filter(p=>p.status!=="inactive"&&p.status!=="sold"&&p.status!=="Sold Out"&&p.status!=="Rented Out"&&p.sold!==true)}
function card(p){const b=brokers[p.brokerUid]||{},phone=digits(p.phone||p.brokerPhone||b.phone),photos=photosOf(p),description=descriptionOf(p),title=p.title||"Property";return `<div class="panel property" data-property-id="${esc(p.id||"")}"><h3>${esc(title)}</h3><div class="rt-lock">📍 ${esc(p.area||p.location||"Location not specified")}</div><div class="details"><div class="detail"><span>TYPE</span><b>${esc(typeOf(p))}</b></div><div class="detail"><span>PRICE / RENT</span><b>${esc(p.price||p.rent||"On Request")}</b></div></div>${p.deposit?`<div class="rt-lock" style="margin-top:7px"><b>Deposit:</b> ${esc(p.deposit)}</div>`:""}${p.size?`<div class="rt-lock"><b>Area:</b> ${esc(p.size)}</div>`:""}${description?`<p>${esc(description)}</p>`:""}${photos.length?`<div class="rt-media">${photos.slice(0,10).map(u=>`<img class="rt-photo" src="${esc(u)}" alt="Property photo">`).join("")}</div>`:""}<div class="badge">Broker: ${esc(b.fullName||p.brokerName||p.broker||"Realynk Broker")}</div><div class="rt-actions" style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"><button type="button" data-cat-call="${phone}">📞 Call Broker</button><button type="button" data-cat-wa="${phone}" data-title="${esc(title)}">💬 WhatsApp</button><button type="button" data-cat-share="${esc(p.id||"")}" data-title="${esc(title)}">↗️ Share</button></div></div>`}
function render(filter=""){activeFilter=filter||"";const out=$("homeList");if(!out)return;let list=allProperties();if(filter)list=list.filter(p=>{const t=norm(typeOf(p));return t===norm(filter)||(filter==="Heavy Deposit"&&(t.includes("heavy")||norm(p.title).includes("heavy deposit")))});const q=$("search")?.value?.trim().toLowerCase();if(q)list=list.filter(p=>[p.title,p.area,p.location,descriptionOf(p),typeOf(p),p.brokerName,p.broker].join(" ").toLowerCase().includes(q));const bar=$("filterBar"),title=$("filterTitle");if(bar)bar.style.display=filter?"flex":"none";if(title)title.textContent=filter?filter+" Properties":"";if(!list.length){out.innerHTML=`<div class="panel empty">No ${esc(filter||"")} properties posted yet.</div>`;return}out.innerHTML=list.map(card).join("");out.querySelectorAll("[data-cat-call]").forEach(b=>b.dataset.catCall?b.onclick=()=>location.href="tel:+91"+b.dataset.catCall:b.disabled=true);out.querySelectorAll("[data-cat-wa]").forEach(b=>b.dataset.catWa?b.onclick=()=>location.href="https://wa.me/91"+b.dataset.catWa+"?text="+encodeURIComponent("Hi, I found your property on Realynk: "+(b.dataset.title||"Property")):b.disabled=true);out.querySelectorAll("[data-cat-share]").forEach(b=>b.onclick=()=>{const text=(b.dataset.title||"Realynk Property")+"\n\nRealynk — India's Real Estate Agent Network";if(navigator.share)navigator.share({title:b.dataset.title||"Realynk Property",text,url:location.href}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(text+"\n"+location.href).then(()=>alert("Realynk property link copied."))})}
function setFilter(type){activeFilter=type;document.querySelectorAll(".quick button").forEach(b=>b.classList.remove("active"));const id=type==="Heavy Deposit"?"heavyDeposit":type.toLowerCase();$(id)?.classList.add("active");render(type);setTimeout(()=>$ ("homeList")?.scrollIntoView({behavior:"smooth",block:"start"}),60)}
async function syncLocal(){let u=auth.currentUser;try{if(!u)u=(await signInAnonymously(auth)).user}catch{return}const p=localProfile(),list=localProperties();for(const item of list.slice(0,30)){if(!item.id)continue;try{await setDoc(doc(db,"properties",String(item.id)),{...item,brokerUid:item.brokerUid||u.uid,brokerName:item.brokerName||p.agentName||"",brokerPhone:item.brokerPhone||p.accountPhone||"",phone:item.phone||p.accountPhone||"",updatedAt:serverTimestamp()},{merge:true})}catch(e){console.warn("Realynk local property sync failed",e)}}}
function start(){document.addEventListener("click",e=>{const button=e.target.closest?.("#buy,#sale,#rent,#commercial,#heavyDeposit");if(button){const type=button.id==="heavyDeposit"?"Heavy Deposit":button.id[0].toUpperCase()+button.id.slice(1);e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();setFilter(type);return}if(e.target.closest?.("#clearFilter")){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();activeFilter="";if($("search"))$("search").value="";document.querySelectorAll(".quick button").forEach(b=>b.classList.remove("active"));render("")}},true);$("search")?.addEventListener("input",()=>render(activeFilter));onSnapshot(collection(db,"brokers"),snap=>{brokers={};snap.forEach(d=>brokers[d.id]=d.data());render(activeFilter)});onSnapshot(collection(db,"properties"),snap=>{cloudProperties=[];snap.forEach(d=>cloudProperties.push({...d.data(),id:d.id}));render(activeFilter)});setTimeout(()=>render(activeFilter),500);setTimeout(()=>render(activeFilter),1800);syncLocal();setInterval(syncLocal,8000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
