import { getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, doc, setDoc, collection, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);let currentUser=null,syncTimer=null;
const readJSON=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||"");return v??f}catch(_){return f}},profile=()=>readJSON("realynkBrokerProfile",{}),properties=()=>{const p=readJSON("realynkProperties",[]);return Array.isArray(p)?p:[]};
const dataUrlToBlob=u=>{const x=String(u||"").split(",");if(x.length!==2)return null;const mime=(x[0].match(/data:([^;]+)/)||[])[1]||"application/octet-stream",bin=atob(x[1]),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime})};
async function syncProfile(){if(!currentUser)return;const p=profile();if(!p.agentName&&!p.accountPhone&&!p.agentEmail)return;await setDoc(doc(db,"brokers",currentUser.uid),{uid:currentUser.uid,fullName:p.agentName||"",phone:p.accountPhone||p.firebasePhone||"",email:p.agentEmail||currentUser.email||"",companyName:p.companyName||"",city:p.city||"",state:p.state||"",mobileVerified:!!p.mobileVerified,emailVerified:!!p.emailVerified,updatedAt:serverTimestamp()},{merge:true})}
async function uploadPropertyMedia(p){if(!currentUser||!p||!p.id)return p;const out={...p},media=Array.isArray(p.photos)?p.photos:[],urls=[];for(let i=0;i<media.length&&i<10;i++){const blob=dataUrlToBlob(media[i]);if(!blob)continue;const snap=await uploadBytes(ref(storage,`properties/${currentUser.uid}/${p.id}/photo-${i+1}`),blob,{contentType:blob.type});urls.push(await getDownloadURL(snap.ref))}if(urls.length)out.photoUrls=urls;return out}
async function syncLatestProperty(){if(!currentUser)return;const list=properties(),p=list[0];if(!p||!p.id)return;try{const cp=await uploadPropertyMedia(p);await setDoc(doc(collection(db,"properties"),String(p.id)),{...cp,brokerUid:currentUser.uid,syncedAt:serverTimestamp()},{merge:true});window.dispatchEvent(new CustomEvent("realynkCloudSync",{detail:{type:"property",id:p.id}}))}catch(e){console.warn("Realynk cloud property sync failed",e)}}
function scheduleProfileSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncProfile().catch(e=>console.warn("Realynk cloud profile sync failed",e)),500)}
onAuthStateChanged(auth,u=>{currentUser=u||null;if(currentUser)syncProfile().catch(e=>console.warn("Realynk cloud profile sync failed",e))});window.addEventListener("storage",e=>{if(e.key==="realynkBrokerProfile")scheduleProfileSync()});const originalSetItem=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){originalSetItem(k,v);if(k==="realynkBrokerProfile")scheduleProfileSync()};const submit=document.getElementById("submit");if(submit)submit.addEventListener("click",()=>setTimeout(()=>syncLatestProperty(),1200),true);window.realynkCloudSync={syncProfile,syncLatestProperty};
for(const [src,v] of [["./realynk-core.js",6],["./realynk-network.js",2],["./category-fix.js",3],["./realynk-final-ui.js",2],["./realynk-app-patch.js",1],["./property-edit.js",2],["./property-management.js",1]]){const s=document.createElement("script");s.type="module";s.src=src+"?v="+v;document.head.appendChild(s)}
