import { getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, doc, setDoc, collection, serverTimestamp, getDocs } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const ADMIN_EMAIL="seagullairexpress@gmail.com";
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);let currentUser=null,syncTimer=null;
const isAdminUser=()=>String(currentUser?.email||"").toLowerCase()===ADMIN_EMAIL;
const readJSON=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||"");return v??f}catch(_){return f}},profile=()=>readJSON("realynkBrokerProfile",{}),properties=()=>{const p=readJSON("realynkProperties",[]);return Array.isArray(p)?p:[]};
const saveProperties=p=>{try{localStorage.setItem("realynkProperties",JSON.stringify(p));return true}catch(_){return false}};
const dataUrlToBlob=u=>{const x=String(u||"").split(",");if(x.length!==2)return null;const mime=(x[0].match(/data:([^;]+)/)||[])[1]||"application/octet-stream",bin=atob(x[1]),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:mime})};
async function syncProfile(){if(!currentUser||isAdminUser())return;const p=profile();if(!p.agentName&&!p.accountPhone&&!p.agentEmail)return;await setDoc(doc(db,"brokers",currentUser.uid),{uid:currentUser.uid,fullName:p.agentName||"",phone:p.accountPhone||p.firebasePhone||"",email:p.agentEmail||currentUser.email||"",companyName:p.companyName||"",city:p.city||"",state:p.state||"",mobileVerified:!!p.mobileVerified,emailVerified:!!p.emailVerified,approved:p.status==='verified',verified:p.status==='verified',status:p.status||"pending",updatedAt:serverTimestamp()},{merge:true})}
async function uploadPropertyMedia(p){if(!currentUser||!p||!p.id)return p;const out={...p},media=Array.isArray(p.photos)?p.photos:[],urls=[];for(let i=0;i<media.length&&i<10;i++){const blob=dataUrlToBlob(media[i]);if(!blob)continue;try{const snap=await uploadBytes(ref(storage,`properties/${currentUser.uid}/${p.id}/photo-${i+1}`),blob,{contentType:blob.type});urls.push(await getDownloadURL(snap.ref))}catch(e){console.warn("Realynk cloud photo upload failed",e)}}if(urls.length)out.photoUrls=urls;if(window.realynkMedia&&typeof window.realynkMedia.getVideo==='function'){try{const v=await window.realynkMedia.getVideo(p.id);if(v&&v.blob){const snap=await uploadBytes(ref(storage,`properties/${currentUser.uid}/${p.id}/property-video`),v.blob,{contentType:v.type||v.blob.type||"video/mp4"});out.videoUrl=await getDownloadURL(snap.ref);out.videoStoragePath=snap.ref.fullPath;out.videoName=v.name||p.videoName||"property-video";out.videoSize=v.size||v.blob.size}}catch(e){console.warn("Realynk cloud video upload failed",e)}}return out}
async function syncProperty(p){if(!currentUser||!p||!p.id)return;if(p.brokerUid&&p.brokerUid!==currentUser.uid)return;try{const cp=await uploadPropertyMedia(p);await setDoc(doc(db,"properties",String(p.id)),{...cp,brokerUid:currentUser.uid,syncedAt:serverTimestamp()},{merge:true})}catch(e){console.warn("Realynk cloud property sync failed",e)}}
async function syncAllLocalProperties(){if(!currentUser)return;const list=properties();for(const p of list)await syncProperty(p)}
async function restoreCloudProperties(){try{const snap=await getDocs(collection(db,"properties"));if(snap.empty)return;const local=properties(),map={};local.forEach(p=>map[String(p.id)]=p);snap.forEach(d=>{const remote=d.data();const id=String(remote.id||d.id);map[id]={...(map[id]||{}),...remote,id:remote.id||d.id,photos:Array.isArray(map[id]?.photos)?map[id].photos:[]}});const merged=Object.values(map).sort((a,b)=>Number(b.id||0)-Number(a.id||0));saveProperties(merged);window.dispatchEvent(new Event("realynkCloudPropertiesRestored"))}catch(e){console.warn("Realynk cloud restore failed",e)}}
async function syncLatestProperty(){if(!currentUser)return;const list=properties();if(list[0])await syncProperty(list[0])}
function scheduleProfileSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncProfile().catch(e=>console.warn("Realynk cloud profile sync failed",e)),500)}
onAuthStateChanged(auth,async u=>{currentUser=u||null;if(currentUser){await syncProfile().catch(e=>console.warn("Realynk cloud profile sync failed",e));await syncAllLocalProperties().catch(e=>console.warn("Realynk cloud property batch sync failed",e));await restoreCloudProperties()}});
window.addEventListener("storage",e=>{if(e.key==="realynkBrokerProfile")scheduleProfileSync()});
const originalSetItem=localStorage.setItem.bind(localStorage);if(!window.__REALYNK_STORAGE_PATCHED__){window.__REALYNK_STORAGE_PATCHED__=true;localStorage.setItem=function(k,v){originalSetItem(k,v);if(k==="realynkBrokerProfile")scheduleProfileSync()}};
const submit=document.getElementById("submit");if(submit&&!submit.__realynkCloudBound){submit.__realynkCloudBound=true;submit.addEventListener("click",()=>setTimeout(()=>syncLatestProperty(),2500),true)}
window.realynkCloudSync={syncProfile,syncLatestProperty,syncAllLocalProperties,restoreCloudProperties};
