(function(){
  function lang(){return localStorage.getItem('realynkLang')||'en'}
  function hd(k){var l=lang(),d={en:{heavyDeposit:'Heavy Deposit',featured:'Properties',edit:'✎ Edit Listing',save:'Save Changes',cancel:'Cancel',title:'Property Title',area:'Area / Location',type:'Listing Type',price:'Price / Rent',deposit:'Deposit',size:'Carpet / Usable Area',desc:'Description',phone:'Contact / WhatsApp',photos:'Replace Photos (optional)',otpTitle:'Mobile OTP Verification',otpHint:'Enter the OTP sent to your mobile number.',sendOtp:'Send OTP',verifyOtp:'Verify OTP',otpPending:'SMS OTP is ready to be connected with Firebase Phone Authentication.',otpNotReady:'SMS OTP is not connected yet. Firebase Phone Authentication setup is required.',otpVerified:'✓ Mobile number verified',otpSent:'OTP option selected'},hi:{heavyDeposit:'हेवी डिपॉजिट',featured:'प्रॉपर्टीज',edit:'✎ लिस्टिंग एडिट करें',save:'बदलाव सेव करें',cancel:'रद्द करें',title:'प्रॉपर्टी का शीर्षक',area:'एरिया / लोकेशन',type:'लिस्टिंग प्रकार',price:'कीमत / किराया',deposit:'डिपॉजिट',size:'कारपेट / उपयोगी क्षेत्र',desc:'विवरण',phone:'कॉन्टैक्ट / WhatsApp',photos:'फोटो बदलें (वैकल्पिक)',otpTitle:'मोबाइल OTP सत्यापन',otpHint:'मोबाइल पर आए OTP को दर्ज करें।',sendOtp:'OTP भेजें',verifyOtp:'OTP सत्यापित करें',otpPending:'SMS OTP को Firebase Phone Authentication से जोड़ा जा सकता है।',otpNotReady:'SMS OTP अभी कनेक्ट नहीं है। Firebase Phone Authentication की सेटिंग आवश्यक है।',otpVerified:'✓ मोबाइल नंबर सत्यापित',otpSent:'OTP विकल्प तैयार है'},mr:{heavyDeposit:'हेवी डिपॉझिट',featured:'प्रॉपर्टीज',edit:'✎ लिस्टिंग एडिट करा',save:'बदल सेव्ह करा',cancel:'रद्द करा',title:'प्रॉपर्टीचे शीर्षक',area:'एरिया / लोकेशन',type:'लिस्टिंग प्रकार',price:'किंमत / भाडे',deposit:'डिपॉझिट',size:'कार्पेट / वापरण्यायोग्य क्षेत्र',desc:'वर्णन',phone:'कॉन्टॅक्ट / WhatsApp',photos:'फोटो बदला (ऐच्छिक)',otpTitle:'मोबाइल OTP सत्यापन',otpHint:'मोबाइलवर आलेला OTP द्या.',sendOtp:'OTP पाठवा',verifyOtp:'OTP सत्यापित करा',otpPending:'SMS OTP Firebase Phone Authentication शी जोडता येईल.',otpNotReady:'SMS OTP अजून कनेक्ट केलेले नाही. Firebase Phone Authentication सेटअप आवश्यक आहे.',otpVerified:'✓ मोबाइल नंबर सत्यापित',otpSent:'OTP पर्याय तयार आहे'},gu:{heavyDeposit:'હેવી ડિપોઝિટ',featured:'પ્રોપર્ટીઝ',edit:'✎ લિસ્ટિંગ એડિટ કરો',save:'ફેરફાર સેવ કરો',cancel:'રદ કરો',title:'પ્રોપર્ટીનું શીર્ષક',area:'એરિયા / લોકેશન',type:'લિસ્ટિંગ પ્રકાર',price:'કિંમત / ભાડું',deposit:'ડિપોઝિટ',size:'કાર્પેટ / ઉપયોગી વિસ્તાર',desc:'વર્ણન',phone:'કૉન્ટેક્ટ / WhatsApp',photos:'ફોટા બદલો (વૈકલ્પિક)',otpTitle:'મોબાઇલ OTP ચકાસણી',otpHint:'મોબાઇલ પર આવેલ OTP દાખલ કરો.',sendOtp:'OTP મોકલો',verifyOtp:'OTP ચકાસો',otpPending:'SMS OTP Firebase Phone Authentication સાથે જોડાઈ શકે છે.',otpNotReady:'SMS OTP હજી કનેક્ટ નથી. Firebase Phone Authentication સેટઅપ જરૂરી છે.',otpVerified:'✓ મોબાઇલ નંબર ચકાસાયેલ',otpSent:'OTP વિકલ્પ તૈયાર છે'}};return(d[l]&&d[l][k])||d.en[k]||k}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
  function getProps(){try{var p=JSON.parse(localStorage.getItem('realynkProperties')||'[]');return Array.isArray(p)?p:[]}catch(e){return[]}}
  function saveProps(p){try{localStorage.setItem('realynkProperties',JSON.stringify(p));return true}catch(e){return false}}
  function toast(msg){var b=document.getElementById('toast');if(b){b.textContent=msg;b.style.display='block';clearTimeout(window.__rkToast);window.__rkToast=setTimeout(function(){b.style.display='none'},2600)}}
  function setupHeavyDeposit(){
    var commercial=document.getElementById('commercial'), post=document.getElementById('postQuick');
    if(!commercial||!post)return;
    if(!document.getElementById('heavyDeposit')){
      var b=document.createElement('button');b.id='heavyDeposit';b.type='button';b.innerHTML='🔐<b data-hd>Heavy Deposit</b>';
      post.parentNode.insertBefore(b,post);
      b.onclick=function(){var search=document.getElementById('search');if(search){search.value='Heavy Deposit';search.dispatchEvent(new Event('input',{bubbles:true}));}var title=document.getElementById('filterTitle'),bar=document.getElementById('filterBar');if(bar){bar.style.display='flex';if(title)title.textContent=hd('heavyDeposit')+' '+hd('featured');}};
    }
    var type=document.getElementById('type');
    if(type&&!type.querySelector('option[value="Heavy Deposit"]')){var o=document.createElement('option');o.value='Heavy Deposit';o.setAttribute('data-hd-key','heavyDeposit');type.appendChild(o)}
    updateHeavyText();
  }
  function updateHeavyText(){var b=document.querySelector('#heavyDeposit [data-hd]');if(b)b.textContent=hd('heavyDeposit');var o=document.querySelector('#type option[value="Heavy Deposit"]');if(o)o.textContent=hd('heavyDeposit')}

  function ensureEditStyles(){if(document.getElementById('rkEditStyles'))return;var s=document.createElement('style');s.id='rkEditStyles';s.textContent='.rkEditBtn{margin-top:8px;width:100%;background:#fff!important;color:#0b3768!important;border:1px solid #dfe6ee!important}.rkModal{position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:100;display:flex;align-items:flex-end;justify-content:center}.rkModalCard{background:#fff;width:min(760px,100%);max-height:92vh;overflow:auto;border-radius:22px 22px 0 0;padding:18px}.rkModalCard h3{margin:0 0 14px;color:#0b3768}.rkModalCard label{display:block;font-weight:700;margin:10px 0 6px}.rkModalCard input,.rkModalCard textarea,.rkModalCard select{width:100%;padding:12px;border:1px solid #cfd9e5;border-radius:10px;font-size:16px;box-sizing:border-box}.rkModalCard textarea{min-height:110px}.rkModalActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.rkModalActions button{padding:13px;border-radius:10px;font-weight:800;border:1px solid #dfe6ee;background:#fff;color:#0b3768}.rkModalActions .save{background:#0b3768;color:#fff}.rkOtp{border:1px solid #cfe0ef;background:#f8fbff;border-radius:14px;padding:14px;margin-top:12px}.rkOtpRow{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.rkOtp input{width:100%;padding:12px;border:1px solid #cfd9e5;border-radius:10px;font-size:18px;letter-spacing:4px;box-sizing:border-box}.rkOtp button{padding:12px;border-radius:10px;border:1px solid #cfd9e5;background:#fff;color:#0b3768;font-weight:800}.rkOtp button.primary{background:#0b3768;color:#fff}.rkOtpMsg{font-size:12px;color:#6b7a8c;margin-top:8px;line-height:1.45}';document.head.appendChild(s)}

  function addEditButtons(){
    var list=document.getElementById('myList');if(!list)return;ensureEditStyles();var cards=list.querySelectorAll('.property');var mine=getProps().filter(function(p){return p.mine});
    cards.forEach(function(card,i){if(card.querySelector('.rkEditBtn'))return;var b=document.createElement('button');b.type='button';b.className='rkEditBtn';b.textContent=hd('edit');b.onclick=function(){openEditor(i)};card.appendChild(b)})
  }
  function openEditor(mineIndex){
    var props=getProps(), mine=props.filter(function(p){return p.mine}), p=mine[mineIndex];if(!p){toast('Listing not found');return}ensureEditStyles();
    var modal=document.createElement('div');modal.className='rkModal';modal.id='rkEditModal';
    modal.innerHTML='<div class="rkModalCard"><h3>'+esc(hd('edit'))+'</h3><label>'+esc(hd('title'))+'</label><input id="rkEt" value="'+esc(p.title||'')+'"><label>'+esc(hd('area'))+'</label><input id="rkEa" value="'+esc(p.area||'')+'"><label>'+esc(hd('type'))+'</label><select id="rkEtype"><option>Buy</option><option>Sale</option><option>Rent</option><option>Commercial</option><option>Heavy Deposit</option></select><label>'+esc(hd('price'))+'</label><input id="rkEp" value="'+esc(p.price||'')+'"><label>'+esc(hd('deposit'))+'</label><input id="rkEd" value="'+esc(p.deposit||'')+'"><label>'+esc(hd('size'))+'</label><input id="rkEs" value="'+esc(p.size||'')+'"><label>'+esc(hd('desc'))+'</label><textarea id="rkEx">'+esc(p.desc||'')+'</textarea><label>'+esc(hd('phone'))+'</label><input id="rkEph" inputmode="numeric" value="'+esc(p.phone||'')+'"><label>'+esc(hd('photos'))+'</label><input id="rkEphotos" type="file" accept="image/*" multiple><div class="small" style="margin-top:6px">Existing photos stay unless new photos are selected.</div><div class="rkModalActions"><button type="button" id="rkCancel">'+esc(hd('cancel'))+'</button><button type="button" class="save" id="rkSave">'+esc(hd('save'))+'</button></div></div>';
    document.body.appendChild(modal);document.getElementById('rkEtype').value=p.type||'Buy';document.getElementById('rkCancel').onclick=function(){modal.remove()};
    document.getElementById('rkSave').onclick=function(){var all=getProps(), target=all.find(function(x){return x.id===p.id});if(!target){modal.remove();return}target.title=document.getElementById('rkEt').value.trim();target.area=document.getElementById('rkEa').value.trim();target.type=document.getElementById('rkEtype').value;target.price=document.getElementById('rkEp').value.trim();target.deposit=document.getElementById('rkEd').value.trim();target.size=document.getElementById('rkEs').value.trim();target.desc=document.getElementById('rkEx').value.trim();target.phone=document.getElementById('rkEph').value.trim();var files=Array.from(document.getElementById('rkEphotos').files||[]);if(files.length){var jobs=files.slice(0,10).map(function(f){return new Promise(function(resolve){var r=new FileReader();r.onload=function(){resolve(r.result)};r.readAsDataURL(f)})});Promise.all(jobs).then(function(arr){target.photos=arr;saveProps(all);modal.remove();location.reload()})}else{saveProps(all);modal.remove();location.reload()}};
  }

  function addOtpBox(){
    var box=document.querySelector('#account .verifyBox');if(!box||document.getElementById('rkOtpBox'))return;ensureEditStyles();
    var wrap=document.createElement('div');wrap.id='rkOtpBox';wrap.className='rkOtp';wrap.innerHTML='<b>'+esc(hd('otpTitle'))+'</b><div class="rkOtpMsg">'+esc(hd('otpHint'))+'</div><div class="rkOtpRow"><input id="rkOtpInput" inputmode="numeric" maxlength="6" placeholder="••••••"><button type="button" id="rkSendOtp">'+esc(hd('sendOtp'))+'</button></div><button type="button" id="rkVerifyOtp" class="primary full" style="margin-top:8px">'+esc(hd('verifyOtp'))+'</button><div id="rkOtpMsg" class="rkOtpMsg">'+esc(hd('otpNotReady'))+'</div>';
    box.appendChild(wrap);
    document.getElementById('rkSendOtp').onclick=function(){toast(hd('otpNotReady'));document.getElementById('rkOtpInput').focus()};
    document.getElementById('rkVerifyOtp').onclick=function(){toast(hd('otpNotReady'))};
  }
  function setup(){setupHeavyDeposit();addOtpBox();addEditButtons();updateHeavyText()}
  window.addEventListener('load',setup);setup();
  var obs=new MutationObserver(function(){setup()});obs.observe(document.body,{childList:true,subtree:true});
  var l=document.getElementById('lang');if(l)l.addEventListener('change',function(){setTimeout(setup,50)});
})();