/* REALYNK BUTTON RECOVERY + HEAVY DEPOSIT CATEGORY */
(function(){
'use strict';
if(window.__REALYNK_RECOVERY__)return;window.__REALYNK_RECOVERY__=true;
function $(id){return document.getElementById(id)}
function getProps(){try{var p=JSON.parse(localStorage.getItem('realynkProperties')||'[]');return Array.isArray(p)?p:[]}catch(e){return[]}}
function saveProps(p){try{localStorage.setItem('realynkProperties',JSON.stringify(p));return true}catch(e){return false}}
function getProfile(){try{return JSON.parse(localStorage.getItem('realynkBrokerProfile')||'{}')||{}}catch(e){return{}}}
function toast(m){var b=$('toast');if(!b)return;b.textContent=m;b.style.display='block';clearTimeout(window.__rkToast);window.__rkToast=setTimeout(function(){b.style.display='none'},2500)}
function show(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});var e=$(id);if(!e)return;e.classList.add('active');document.querySelectorAll('[data-nav]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-nav')===id)});window.scrollTo(0,0);if(id==='home')renderHome();if(id==='dashboard')renderDashboard();if(id==='account')fillAccount();if(id==='brokers')renderBroker()}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function card(p){var phone=String(p.phone||getProfile().accountPhone||'9658364364').replace(/\D/g,'');return '<div class="panel property"><h3>'+esc(p.title||'Property')+'</h3><div>📍 '+esc(p.area||'Location not specified')+'</div><div class="details"><div class="detail"><span>TYPE</span><b>'+esc(p.type||'')+'</b></div><div class="detail"><span>PRICE</span><b>'+esc(p.price||'On Request')+'</b></div></div><div style="margin-top:10px">'+esc(p.desc||'')+'</div><div><span class="badge">Active</span></div><div style="margin-top:10px;display:flex;gap:8px;flex-wrap:wrap"><button type="button" data-rk="call" data-phone="'+phone+'">📞 Call</button><button type="button" data-rk="wa" data-phone="'+phone+'">WhatsApp</button><button type="button" data-rk="share">↗ Share</button></div></div>'}
function renderHome(){var q=(($('search')||{}).value||'').trim().toLowerCase();var list=getProps().filter(function(p){return !q||[p.title,p.area,p.type,p.desc,p.size,p.deposit].join(' ').toLowerCase().indexOf(q)>=0});if($('homeList'))$('homeList').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No properties posted yet.</div>';if($('filterBar'))$('filterBar').style.display=q?'flex':'none';if($('filterTitle'))$('filterTitle').textContent=q?'Showing: '+q:''}
function renderDashboard(){var m=getProps().filter(function(p){return p.mine});if($('count'))$('count').textContent=m.length;if($('leadCount'))$('leadCount').textContent='0';if($('favCount'))$('favCount').textContent='0';if($('myList'))$('myList').innerHTML=m.length?m.map(card).join(''):'<div class="empty">Your posted properties will appear here.</div>'}
function fillAccount(){var p=getProfile();['agentName','accountPhone','agentEmail','accountType','companyName','officeAddress','city','state','pincode','experience','specialization','serviceAreas','reraNo','reraCompetency','gstin','website'].forEach(function(id){if($(id)&&p[id]!=null)$(id).value=p[id]});if($('declaration'))$('declaration').checked=!!p.declaration}
function renderBroker(){var b=$('brokerProfileCard'),p=getProfile();if(!b)return;if(!p.agentName){b.innerHTML='<b>Broker profile not created yet.</b><p class="small">Create your broker account to join the Realynk network.</p><button id="rkCreateBroker" class="primary full" type="button">Create Broker Account</button>';var c=$('rkCreateBroker');if(c)c.onclick=function(){show('account')};return}b.innerHTML='<div class="profileName">'+esc(p.agentName)+'</div><div class="profileCompany">'+esc(p.companyName||'Individual Broker / Agent')+'</div><div class="small">'+esc(p.city||'')+(p.state?', '+esc(p.state):'')+'</div><span class="badge pending">Pending Review</span>'}
function saveAccount(){var n=($('agentName')||{}).value.trim(),ph=($('accountPhone')||{}).value.trim(),c=($('city')||{}).value.trim(),s=($('state')||{}).value.trim();if(!n||!ph||!c||!s){toast('Please fill Name, Mobile, City and State');show('account');return}if(!/^\d{10}$/.test(ph)){toast('Enter a valid 10-digit mobile number');return}if($('declaration')&&!$('declaration').checked){toast('Please confirm the declaration');return}var p=getProfile();p.agentName=n;p.accountPhone=ph;p.agentEmail=($('agentEmail')||{}).value.trim();p.accountType=($('accountType')||{}).value;p.companyName=($('companyName')||{}).value.trim();p.officeAddress=($('officeAddress')||{}).value.trim();p.city=c;p.state=s;p.pincode=($('pincode')||{}).value.trim();p.experience=($('experience')||{}).value;p.specialization=($('specialization')||{}).value.trim();p.serviceAreas=($('serviceAreas')||{}).value.trim();p.reraNo=($('reraNo')||{}).value.trim();p.reraCompetency=($('reraCompetency')||{}).value.trim();p.gstin=($('gstin')||{}).value.trim();p.website=($('website')||{}).value.trim();p.declaration=true;p.status=p.status||'pending';localStorage.setItem('realynkBrokerProfile',JSON.stringify(p));toast('Broker account saved. Verification is pending.');show('brokers')}
function submitProperty(){var t=($('title')||{}).value.trim();if(!t){toast('Please enter Property Title');show('post');return}var p=getProfile();if(!p.agentName){toast('Please create your Broker Account first');show('account');return}var item={id:Date.now(),title:t,area:($('area')||{}).value.trim(),type:($('type')||{}).value,price:($('price')||{}).value.trim(),deposit:($('deposit')||{}).value.trim(),size:($('size')||{}).value.trim(),desc:($('desc')||{}).value.trim(),phone:($('phone')||{}).value.trim()||p.accountPhone||'9658364364',mine:true,photos:[],broker:p.agentName,brokerStatus:p.status||'pending'};var files=Array.from(($('photos')||{}).files||[]).slice(0,10);Promise.all(files.map(function(f){return new Promise(function(r){var x=new FileReader();x.onload=function(){r(x.result)};x.readAsDataURL(f)})})).then(function(a){item.photos=a;var all=getProps();all.unshift(item);if(saveProps(all)){toast('Property posted successfully');['title','area','price','deposit','size','desc'].forEach(function(id){if($(id))$(id).value=''});if($('photos'))$('photos').value='';show('dashboard')}})}
function setup(){document.querySelectorAll('[data-nav]').forEach(function(b){b.onclick=function(e){e.preventDefault();show(b.getAttribute('data-nav'))}});document.querySelectorAll('[data-back]').forEach(function(b){b.onclick=function(e){e.preventDefault();show(b.getAttribute('data-back'))}});['postQuick','brokerPost','add'].forEach(function(id){var b=$(id);if(b)b.onclick=function(){show('post')}});['buy','sale','rent','commercial'].forEach(function(id){var b=$(id);if(b)b.onclick=function(){if($('search'))$('search').value=id==='buy'?'Buy':id==='sale'?'Sale':id==='rent'?'Rent':'Commercial';show('home')}});if($('search'))$('search').oninput=renderHome;if($('clearFilter'))$('clearFilter').onclick=function(){if($('search'))$('search').value='';renderHome()};if($('submit'))$('submit').onclick=submitProperty;if($('saveAccount'))$('saveAccount').onclick=saveAccount;if($('lang'))$('lang').onchange=function(){localStorage.setItem('realynkLang',this.value);location.reload()};if($('type')){var opt=$('type').querySelector('option[value="Heavy Deposit"]');if(!opt){opt=document.createElement('option');opt.value='Heavy Deposit';opt.textContent='Heavy Deposit';$('type').appendChild(opt)}$('type').onchange=function(){var v=$('type').value;if($('depositField'))$('depositField').style.display=(v==='Rent'||v==='Heavy Deposit')?'block':'none';if($('sizeField'))$('sizeField').style.display=(v==='Sale'||v==='Commercial'||v==='Heavy Deposit')?'block':'none'}}var q=document.querySelector('.quick');if(q&&!$('heavyDeposit')){var h=document.createElement('button');h.id='heavyDeposit';h.type='button';h.innerHTML='🔐<b>Heavy Deposit</b>';q.insertBefore(h,$('postQuick'));h.onclick=function(){if($('search'))$('search').value='Heavy Deposit';show('home');renderHome()}}renderHome();renderDashboard();fillAccount();renderBroker()}
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-rk]');if(!b)return;var a=b.getAttribute('data-rk'),ph=b.getAttribute('data-phone')||'';if(a==='call')location.href='tel:+91'+ph;if(a==='wa')window.open('https://wa.me/91'+ph,'_blank');if(a==='share'){if(navigator.share)navigator.share({title:'REALYNK Property',url:location.href}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(function(){toast('Property link copied')})}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();window.addEventListener('load',setup);
})();