// Realynk plan UI — pricing presentation only; payment/billing will be connected later.
(function(){'use strict';
const plans=[
 {name:'FREE',price:'₹0',period:'Launch access',tag:'First 30 Days',features:['Basic broker profile','Up to 5 active properties','Basic enquiries','Call & WhatsApp']},
 {name:'BASIC',price:'₹99',period:'/ month',tag:'For individual brokers',features:['Up to 20 active properties','Lead & enquiry management','Call & WhatsApp','Basic performance insights']},
 {name:'PREMIUM',price:'₹249',period:'/ month',tag:'Most Popular',features:['Up to 100 active properties','Priority leads','Property Boost','Advanced insights','Verified Broker profile']},
 {name:'PRO / AGENCY',price:'₹499',period:'/ month',tag:'For teams & agencies',features:['High listing limit','Multiple team members','Lead assignment','Reports & analytics','Agency profile']}
];
function css(){if(document.getElementById('rl-plan-css'))return;const s=document.createElement('style');s.id='rl-plan-css';s.textContent=`.rl-plans{margin-top:14px}.rl-plan-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.rl-plan-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.rl-plan{border:1px solid #dfe6ee;border-radius:16px;padding:14px;background:#fff}.rl-plan.pop{border:2px solid #f4b400;background:#fffaf0}.rl-plan h4{margin:0;color:#0b3768;font-size:18px}.rl-price{font-size:24px;font-weight:900;color:#0b3768;margin:8px 0 2px}.rl-period{font-size:11px;color:#6b7a8c}.rl-tag{font-size:11px;font-weight:800;color:#18864b;margin:7px 0}.rl-plan ul{padding-left:18px;margin:8px 0 0;color:#44586b;font-size:12px;line-height:1.65}.rl-plan-note{font-size:12px;color:#6b7a8c;line-height:1.5;margin-top:12px}@media(max-width:480px){.rl-plan-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function render(){const account=document.getElementById('account');if(!account||document.getElementById('realynkPlans'))return;css();const host=account.querySelector('.page')||account;const box=document.createElement('section');box.id='realynkPlans';box.className='panel rl-plans';box.innerHTML=`<div class="rl-plan-head"><div><h3 style="margin:0;color:#0b3768">💎 Realynk Plans</h3><div class="rl-plan-note">Start free, then choose the plan that fits your business.</div></div></div><div class="rl-plan-grid">${plans.map(p=>`<article class="rl-plan ${p.name==='PREMIUM'?'pop':''}"><h4>${p.name}</h4><div class="rl-price">${p.price} <span class="rl-period">${p.period}</span></div><div class="rl-tag">${p.tag}</div><ul>${p.features.map(x=>`<li>${x}</li>`).join('')}</ul></article>`).join('')}</div><div class="rl-plan-note"><b>Launch Offer:</b> First 30 days free. Paid subscription checkout will be enabled before public launch.</div>`;host.appendChild(box)}
function start(){render();setTimeout(render,500);setTimeout(render,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
