import { getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, onSnapshot, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const ADMIN_EMAIL="seagullairexpress@gmail.com";
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);
const auth=getAuth(app),db=getFirestore(app);let adminUser=null,brokerMap={};
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const digits=v=>String(v||"").replace(/\D/g,"");
function css(){if(document.getElementById("sa-css"))return;const s=document.createElement("style");s.id="sa-css";s.textContent=`.sa-card{border:2px solid #f4b400!important;background:#fffaf0!important}.sa-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.sa-badge{background:#b42318;color:#fff;border-radius:999px;padding:4px 8px;font-size:12px;font-weight:800}.sa-row{border:1px solid #dfe6ee;background:#fff;border-radius:12px;padding:12px;margin:10px 0}.sa-row b{color:#0b3768}.sa-actions{display:flex;gap:8px;margin-top:10px}.sa-actions button{flex:1;border:0;border-radius:10px;padding:11px;font-weight:800}.sa-approve{background:#18864b;color:#fff}.sa-reject{background:#fff;color:#b42318;border:1px solid #e0b8b4!important}.sa-note{font-size:12px;color:#6b7a8c}.sa-entry{border:1px solid #f4b400!important;background:#fffaf0!important;color:#7d5b00!important}`;document.head.appendChild(s)}
function isAdmin(){return String(auth.currentUser?.email||"").toLowerCase()===ADMIN_EMAIL}
function removePanel(){const p=document.getElementById("superAdminPanel");if(p)p.remove()}
function panel(){if(!isAdmin())return removePanel();css();const account=document.getElementById("account");if(!account)return;let box=document.getElementById("superAdminPanel");if(!box){box=document.createElement("div");box.id="superAdminPanel";box.className="panel sa-card";account.querySelector(".page")?.appendChild(box)}const all=Object.values(brokerMap).filter(b=>String(b.email||"").toLowerCase()!==ADMIN_EMAIL);const pending=all.filter(b=>b.approved!==true);box.innerHTML=`<div class="sa-head"><div><h3 style="margin:0;color:#0b3768">👑 SUPER ADMIN</h3><div class="sa-note">Administrator access</div></div>${pending.length?`<span class="sa-badge">${pending.length} PENDING</span>`:`<span class="sa-note">No pending brokers</span>`}</div>${pending.length?pending.map(b=>{const ph=digits(b.phone);return `<div class="sa-row"><b>${esc(b.fullName||"New Broker")}</b><div class="sa-note">${esc(b.companyName||"Broker / Agent")} • ${esc(b.city||"")}, ${esc(b.state||"")}</div><div class="sa-note">📱 ${esc(b.phone||"Not provided")} ${b.email?`• ✉️ ${esc(b.email)}`:""}</div><div class="sa-actions"><button class="sa-approve" data-sa-approve="${esc(b.uid)}">✓ Approve</button><button class="sa-reject" data-sa-reject="${esc(b.uid)}">Reject</button>${ph?`<button data-sa-call="${ph}" style="background:#fff;border:1px solid #dfe6ee">📞</button>`:""}</div></div>`}).join(""):"<div class=\"sa-note\" style=\"padding:12px 0\">New broker registrations will appear here automatically.</div>"}`;
box.querySelectorAll("[data-sa-approve]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await updateDoc(doc(db,"brokers",b.dataset.saApprove),{approved:true,verified:true,status:"verified",approvedAt:serverTimestamp()});}catch(e){alert("Approval failed. Check Firebase permissions.");b.disabled=false}});
box.querySelectorAll("[data-sa-reject]").forEach(b=>b.onclick=async()=>{if(!confirm("Reject this broker?"))return;try{await updateDoc(doc(db,"brokers",b.dataset.saReject),{approved:false,verified:false,status:"rejected",rejectedAt:serverTimestamp()})}catch(e){alert("Reject failed. Check Firebase permissions.")}});
box.querySelectorAll("[data-sa-call]").forEach(b=>b.onclick=()=>location.href="tel:+91"+b.dataset.saCall);
}
function start(){onAuthStateChanged(auth,u=>{adminUser=String(u?.email||"").toLowerCase()===ADMIN_EMAIL?u:null;if(adminUser)panel();else removePanel()});onSnapshot(collection(db,"brokers"),snap=>{brokerMap={};snap.forEach(d=>brokerMap[d.id]=d.data());if(adminUser)panel()},e=>{console.warn("Realynk Super Admin broker watch failed",e);if(adminUser)panel()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();